---
- name: Install NTP
  yum: >
    name=ntp
    state=installed

- name: Copy NTP configuration file
  template: >
    src=ntp.conf.j2
    dest=/etc/ntp.conf
    owner=root
    group=root
    mode=0664
  notify: restart_ntpd

- name: Create /etc/ntp/step-tickers file
  template: >
    src=step-tickers.j2
    dest=/etc/ntp/step-tickers
    owner=root
    group=root
    mode=0664
  notify: restart_ntpd

- name: Set /etc/localtime file
  file: >
    src=/usr/share/zoneinfo/{{ ntp_config_timezone }}
    dest=/etc/localtime
    force=yes
    state=link
  notify: restart_ntpd

- name: Set /etc/sysconfig/clock file
  template: >
    src=clock.j2
    dest=/etc/sysconfig/clock
    owner=root
    group=root
    mode=0644
  notify: restart_ntpd

- name: Start and enable NTP service
  service: >
    name=ntpd
    state=started
    enabled=yes
  when: ntp_config_enabled == True
